name = "Dodds-Watts_model"
uuid = "d11a19ef-9e87-48cc-80b2-5067439fd692"
authors = ["Leander Schwarzmeier <leander-schwarzmeier@web.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
